title: CS Workshop - 2020
description: Code Switching Workshop
details: Collocated with LREC 2020
github:
  owner_name: Jason
  wi_url: wi.html
  oc_url: oc.html
  pc_url: pc.html
dates:
  - name: Workshop date
    date: Saturday May 16th, 2020
  - name: Paper submission
    date: February 20th, 2020
  - name: Notification of acceptance
    date: March 16th, 2020
  - name: Camera ready submission deadline
    date: April 5th, 2020
Links: https://lrec2020.lrec-conf.org/en/
Venue: Le Palais du Pharo